-----Pull all information

SELECT * 
FROM CASESTUDY.BRIGHT_COFFEE_SHOP.COFFEE_SHOP;
-------------------------

----Exploratory Data Analysis

---Checking number of coffee stores

SELECT DISTINCT STORE_LOCATION
FROM CASESTUDY.BRIGHT_COFFEE_SHOP.COFFEE_SHOP;

-----Checking number of Product category

SELECT DISTINCT PRODUCT_CATEGORY
FROM CASESTUDY.BRIGHT_COFFEE_SHOP.COFFEE_SHOP;

-----Checking number of Product_Type

SELECT DISTINCT PRODUCT_TYPE
FROM CASESTUDY.BRIGHT_COFFEE_SHOP.COFFEE_SHOP;
--------------------------
---Date and Time Functions

----checking earliest transaction date

SELECT MIN(TRANSACTION_DATE) AS FIRST_OPERATING_DATE
FROM CASESTUDY.BRIGHT_COFFEE_SHOP.COFFEE_SHOP;

----Check latest transaction date

SELECT MAX(TRANSACTION_DATE) AS LAST_OPERATIN_DATE
FROM CASESTUDY.BRIGHT_COFFEE_SHOP.COFFEE_SHOP;

----checking earliest time

SELECT MIN(TRANSACTION_TIME) AS EARLIEST_TIME
FROM CASESTUDY.BRIGHT_COFFEE_SHOP.COFFEE_SHOP;

----Check latest transaction date

SELECT MAX(TRANSACTION_TIME) AS LAST_OPERATIN_TIME
FROM CASESTUDY.BRIGHT_COFFEE_SHOP.COFFEE_SHOP;
----------------------------------------------
SELECT TRANSACTION_DATE,
       DAYNAME(TRANSACTION_DATE) AS DAY_NAME,
       CASE
            WHEN DAYNAME(TRANSACTION_DATE) IN ('SAT','SUN') THEN 'WEEKEND'
            ELSE 'WEEKDAY'
       END AS Day_Classification,
       MONTHNAME(TRANSACTION_DATE) AS MONTH_NAME,
       TRANSACTION_TIME,
       CASE
           WHEN TRANSACTION_TIME BETWEEN '06:00:00' AND '11:59:59' THEN 'MORNING'
           WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '16:59:59' THEN 'AFTERNOON'
           WHEN TRANSACTION_TIME >= '17:00:00' THEN 'EVENING'
       END AS TIME_BUCKET,
      HOUR(TRANSACTION_TIME) AS HOUR_OF_DAY,
      STORE_LOCATION,
      PRODUCT_CATEGORY,
      PRODUCT_TYPE,
      PRODUCT_DETAIL,
      UNIT_PRICE,
      TRANSACTION_QTY,
      TRANSACTION_QTY*UNIT_PRICE AS REVENUE
FROM CASESTUDY.BRIGHT_COFFEE_SHOP.COFFEE_SHOP;

